@file:Suppress("UNUSED_PARAMETER", "unused")

package com.n8n.mobile.studio

/**
 * Offline check stub for classes the Android build generates or that live in the
 * Compose UI layer (which cannot be compiled without the Compose artifacts).
 *
 * The real `R` is generated by AGP from `res/`, and the real `MainActivity` is a
 * Compose activity; only their use from non-UI code (a notification's content
 * intent) is modelled here.
 */
object R {
    object drawable {
        const val ic_stat_runtime = 1
        const val ic_launcher_foreground = 2
    }

    object string {
        const val app_name = 1
    }

    object id {
        const val notification_action = 1
    }
}

class MainActivity : android.app.Activity()
